### ISSUE TITLE
Firefox installation incomplete?

### ISSUE THREAD

**Issue by romanho** [siemens/linux-entra-sso#18]
First: thank you very much for this extension! It saved my mLinux from silently loosing more and more pages (I've never got Intune + MS Edge working).

But I had a problem during installation, which turned out to be rather simple in the end. Following README.md I called "make local-install-firefox" and expected everything to be in place. But though a lot of Firefox restarts, debug logs and strace I could not see any access to ~/.mozilla/native-messaging-hosts and generally nothing was working. This is the standard firefox-esr_115.12.0esr-1~deb12u1 package from Debian bookworm, BTW.

After some time (we had to reach a milestone) I retried today and gave a chance to the "development version" section of README. I've built and installed the .xpi from build/ and voila -- everything works!

So I guess either just the README misses out some step, or the package fails to provide the announced signed extension ,or the Makefile doesn't install it from "local-install-firefox" target.

**Comment by fmoessbauer** [comment]
Hi, after re-reading the readme, it is indeed a bit misleading what *exactly* needs to be done to get it working on FF. Actually the only missing step was to get the latest "signed" version from the releases.

> You can get a signed version of the browser extension from our Github releases.

We should stress that a bit more by adding it as a last step to the enumeration. I'll prepare a MR.

>  or the package fails to provide the announced signed extension ,or the Makefile doesn't install it from "local-install-firefox" target.

Unfortunately the Makefile itself can't produce the signed extension file (`.xpi`), as this needs to be signed by Mozilla. This step is done via API calls in the github actions and then the signed artifact is added to the release.

**Comment by romanho** [comment]
> Actually the only missing step was to get the latest "signed" version from the releases.
[...]
> We should stress that a bit more by adding it as a last step to the enumeration. I'll prepare a MR

Ah, I now also see "get a signed version [...] from our Github releases" the first part, I obviously missed that and directly went to the enumeration.

Agreed, introducing an explicit step for this is probably the right solution. (And I can get rid of the "unsigned extension" warning :-)
