### ISSUE TITLE
Make the install paths platform dependant

### ISSUE THREAD

**Issue by rutgerputter** [siemens/linux-entra-sso#21]
When using the system-wide option `make install`, the paths should be set based on the distribution/platform.

For instance, RedHat/Fedora have a `/usr/lib` and a `/usr/lib64` folder based on the architecture (i386 or x86_64).

On Fedora/Redhat x86_64, the Mozilla native messaging host should be in in `/usr/lib64/mozilla`
On Debian-family distro's no such distinction is make and everything is put in `/usr/lib`

Also, based on https://www.chromium.org/administrators/linux-quick-start/, the `/etc` folder for Chromium is different. On Fedora it's in `/etc/chromium` and on Ubuntu it's in `/etc/chromium-browser`.

**Comment by jan-kiszka** [comment]
`LIBDIR`, `PREFIX` and likely also `DESTDIR` are needed now, true. Distro packages can then set what they need.
