### ISSUE TITLE
Interactive mode via shell fails

### ISSUE THREAD

**Issue by dimpflmoser** [siemens/linux-entra-sso#42]
When I try to get a token via python script it fails on Debian12:

```
user@debian:~/Download/linux-entra-sso$ python3 linux-entra-sso.py --interactive acquirePrtSsoCookie
Traceback (most recent call last):
  File "/home/userDownload/linux-entra-sso/linux-entra-sso.py", line 296, in <module>
    run_interactive()
  File "/home/user/Download/linux-entra-sso/linux-entra-sso.py", line 283, in run_interactive
    account = accounts['accounts'][args.account]
              ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by fmoessbauer** [comment]
Hi, this happens if no account is registered with Intune (i.e. `len(accounts['accounts']) == 0`). Did you already "onboard" your Intune?

Anyways, I'll add a check that reports a meaningful error message instead of the exception.

**Comment by dimpflmoser** [comment]
Thanks for your quick reply.

That machine is a brand-new installation and enrolment, my first mLinux instance, so I'm not quite sure.
ZScaler works and connects me to Intranet.

According to this file, it looks as if my machine was registered:
```
user@debian:~$ sudo cat /var/opt/siemens/mlinux/devices_with_same_owner.yaml
---
devices_with_same_owner:
  firstname.secondname_0123456789:
    last_seen: 2024-10-31T17:54:09+00:00
    registered: 2024-10-31T17:47:47+00:00
    hostname: debian
    info: 
```

I just saw that enrolment with intune is an extra step. Just tried, but my device doesn't seem to be compliant.
Propably need to fix that first.

**Comment by dimpflmoser** [comment]
Actually after registration at Intune Portal, that error is gone, even though my device is not compliant.
