### ISSUE TITLE
Make install doesn't work on openSUSE

### ISSUE THREAD

**Issue by dmulder** [siemens/linux-entra-sso#47]
Where is it that the browser plugin expects to find the linux-entra-sso python script? I've tried installing it in many different places on openSUSE (with and without the Makefile), but the plugin still doesn't work.

**Comment by dmulder** [comment]
Oh, it was failing because I needed to install pydbus. I'm still unsure of where the plugin expects the script to be though.

**Comment by jan-kiszka** [comment]
Firefox or Chrome family? Firefox looks centrally under `/usr/lib64/mozilla/native-messaging-hosts` for the json file that describes where the script is found. The Chrome paths should fit for what is in the Makefile.

**Comment by dmulder** [comment]
I'm looking at Firefox.

**Comment by dmulder** [comment]
I've added support for this in Himmelblau (an alternative broker to MS Intune), so I want to package your plugin for various distros.

**Comment by jan-kiszka** [comment]
Then check if the `linux_entra_sso.json` under that path exists and which script it points to.

**Comment by jan-kiszka** [comment]
BTW, our Makefile installs to `/usr/lib/mozilla/native-messaging-hosts/` by default - unless you tweak it in your package rule.

**Comment by dmulder** [comment]
Ok, the issue is that `make install` seems to be putting things in the wrong place. The plugin doesn't detect that `linux_entra_sso.json` file. If I do a local install (not sufficient for packaging, obviously), then it does see it.

**Comment by dmulder** [comment]
Also, should a `make install` add the plugin itself in Firefox (it does not)?

**Comment by dmulder** [comment]
Ah, openSUSE expects it to be installed in /usr/lib64/mozilla/native-messaging-hosts/, not /usr/lib/mozilla/native-messaging-hosts/

**Comment by jan-kiszka** [comment]
>Also, should a make install add the plugin itself in Firefox (it does not)?

Nope, enforcing the hook-up in the browser was not intended so far. Chrome has it in its store but Mozilla rejected for not totally clear reasons.

**Comment by dmulder** [comment]
Perhaps you could package the extension in your debian, then call `firefox -install-global-extension linux_entra_sso-1.1.0.xpi`?

**Comment by dmulder** [comment]
Where is the extension in the Chrome webstore? I can't find it. Has it been removed?

**Comment by jan-kiszka** [comment]
https://chromewebstore.google.com/detail/linux-entra-sso/jlnfnnolkbjieggibinobhkjdfbpcohn (see README), but this is apparently not listed in their search database. @fmoessbauer may know more.

**Comment by dmulder** [comment]
> https://chromewebstore.google.com/detail/linux-entra-sso/jlnfnnolkbjieggibinobhkjdfbpcohn (see README), but this is apparently not listed in their search database. @fmoessbauer may know more.

Thanks!

FYI, you can force the extension to install via browser policies:

**/etc/firefox/policies/policies.json**
```json
{
  "policies": {
    "Extensions": {
      "Install": [
        "https://github.com/siemens/linux-entra-sso/releases/download/v1.1.0/linux_entra_sso-1.1.0.xpi"
      ]
    }
  }
}
```

**/etc/opt/chrome/policies/managed/himmelblau.json**
**/etc/chromium/policies/managed/himmelblau.json**
```json
{
  "ExtensionInstallForcelist": [
    "jlnfnnolkbjieggibinobhkjdfbpcohn"
  ]
}
```

**Comment by fmoessbauer** [comment]
> but this is apparently not listed in their search database

We want to avoid that people find and install the extension via the store, forget to install the host parts and complain about it not working.

> FYI, you can force the extension to install via browser policies:

That's what we do internally. But I don't really like the circular dependencies (i.e. having links to the packages on github in the code itself).
