### ISSUE TITLE
Marketplace link broken?

### ISSUE THREAD

**Issue by fgreinacher** [siemens/linux-entra-sso#5]
The [marketplace link from the readme](https://github.com/siemens/linux-entra-sso?tab=readme-ov-file#firefox-via-addonsmozillaorg) does not work: 

<img width="771" alt="image" src="https://github.com/siemens/linux-entra-sso/assets/1540469/4c9253ec-1185-40f5-b339-15ce38e5940d">

**Comment by jan-kiszka** [comment]
Yes, there has been some fuzzy push-back from AMO, @fmoessbauer can tell more.

**Comment by fmoessbauer** [comment]
We got the following review message from Mozilla:

> Our review found that your content violates the following Mozilla policy or policies:
>  Content, specifically Closed user group: Due to the limited/non-public audience of this add-on, this add-on can not be listed on AMO. However, you may submit a self-hosted version and distribute the signed file yourself. For information on self-distribution, see https://extensionworkshop.com/documentation/publish/submitting-an-add-on/#self-distribution. If your add-on had already been approved in the past, please change the listing to &quot;Invisible&quot; on the &quot;Status and Versions&quot; page.

We are currently clarifying this, as a similar extension for windows was also published on AMO. Further, the Windows version of Firefox now has hard-coded support for what the plugin was doing before.

In the meantime, we are considering to self-distributed the signed versions, but that requires some preparations on our side.

**Comment by fgreinacher** [comment]
Thanks for the clarification. Weird that they consider this to target a closed user group 🤨

**Comment by jan-kiszka** [comment]
Might be a misunderstanding, but it is hard to find a way clarifying this with "them".
